name: PBRP Recovery CI (Poco X6 5G)

on:
  workflow_dispatch:

jobs:
  build:
    name: Build PBRP by Cloud
    runs-on: ubuntu-latest

    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Build Packages
      run: |
        sudo apt-get update
        sudo apt-get install -y g++-multilib gcc-multilib lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses5-dev libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev git python3 openjdk-11-jdk bc bison build-essential curl flex gnupg gperf image_utils libelf-dev libx11-dev libgl1-mesa-dev libxml-simple-perl lzma python-is-python3 unzip

    - name: Install Repo Tool
      run: |
        mkdir -p ~/bin
        curl https://googleapis.com > ~/bin/repo
        chmod a+x ~/bin/repo
        sudo ln -sf ~/bin/repo /usr/bin/repo

    - name: Setup Git Config
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"

    - name: Initialize Repo and Sync Source
      run: |
        mkdir pbrp_workspace && cd pbrp_workspace
        repo init -u https://github.com -b android-12.1 --depth=1
        repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags

    - name: Clone Device Tree
      run: |
        cd pbrp_workspace
        git clone https://github.com{{ github.repository }} -b android-12.1 device/xiaomi/garnet

    - name: Build PBRP
      run: |
        cd pbrp_workspace
        export ALLOW_MISSING_DEPENDENCIES=true
        source build/envsetup.sh
        lunch pb_garnet-eng
        mka pbrp

    - name: Upload Recovery Image
      uses: actions/upload-artifact@v4
      with:
        name: PBRP-Poco-X6-5G-Recovery
        path: pbrp_workspace/out/target/product/garnet/recovery.img
